# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme = "congo"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = false
enableCodeCopy = false
enableImageLazyLoading = true
enableImageWebp = true

robots = "all"

[header]
  layout = "basic" # valid options: basic, hamburger, hybrid, custom
  #logo = "assets/icons/favicon-16x16.png"
  #logoDark = "img/dark-logo.jpg"
  # favicon_16 = "assets/icons/favicon-16x16.png"
  showTitle = true

[footer]
  showCopyright = false
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile" # valid options: page, profile, custom
  showRecent = false

